### PR TITLE
New basic heuristics for Audapter

### PR DESCRIPTION
**Pull request by cwnaber**
### Heuristics
Six new heuristics are included in this pull request. None of them required any changes outside of `ost.cpp` and `ost.h`:

* INTENSITY_SLOPE_BELOW_THRESH
   * Checks for the RMS slope being below a certain threshold for a certain duration. Useful for steep declines in RMS slope, such as vowel offset before a stop. [Paired with next heuristic.]
* INTENSITY_SLOPE_ABOVE_THRESH
   * Checks for the RMS slope being above a certain threshold for a certain duration. Potentially useful for vowel onset after a stop. [Paired with previous heuristic.]
* [**REMOVED FROM PR** -- see comments] INTENSITY_BELOW_THRESH_NEG_SLOPE 
   * Checks for the RMS being below a certain threshold for a certain duration, all while the RMS slope is negative. Functionally a replacement to the original INTENSITY_FALL heuristic, which, despite its name, does not consider RMS slope. Useful for detecting vowel offsets.
* INTENSITY_RATIO_BELOW_THRESH_NEG_SLOPE
   *  Checks for the RMS ratio being below a certain threshold for a certain duration, all while the RMS slope is negative.
* INTENSITY_RATIO_ABOVE_THRESH_WITH_RMS_FLOOR
  * Checks for the RMS ratio being above a certain threshold for a certain duration, all while the RMS is above 0.0003. Functionally a replacement for INTENSITY_RATIO_RISE. This new heuristic is useful, because when the RMS is very low, random noise can cause the RMS ratio to go above your target threshold. Useful for fricative onset coming out of silence, such as utterance-initial.
* INTENSITY_AND_RATIO_ABOVE_THRESH
  * Checks for the RMS being above a certain threshold, and the RMS ratio being above another certain threshold, for a certain duration. **This is the first three-parameter heuristic.** Useful for certain kinds of onsets with high RMS intensity and RMS ratio.

### Third input parameter
This PR also adds support for heuristics that require three parameters. Previously, the third input parameter for all heuristics was `{}`. As of now, INTENSITY_AND_RATIO_ABOVE_THRESH is the only heuristic which supports 3 input parameters. All other heuristics should keep using `{}` as the third input parameter.

### Testing
All of these heuristics have been tested and in use internally by me and Robin for the past 4 weeks.

### Mex file
Once this is merged, we can work on distributing the new mex file. See Slack for mex file (not supported on GitHub).

### CODE REVIEW

**Comment by rpkarlin** [comment]
Basic question for me is what to do about the changes in the new_heur branch for audapter_viewer. Some of them are more aesthetic but others are functional (e.g. ability to edit three parameters for INTENSITY_AND_RATIO_ABOVE_THRESH). 

I'm currently in favor of merging current-studies/@new_heur into master. The only thing we might want to branch off or indicate somehow are the options for ratio-slope-based heuristics. audapter_viewer currently has code in for compatibility with data that doesn't have an audapter-supplied ratio-slope, but if we don't branch that we might want to note in audapter_viewer somehow that those heuristics won't be handled by Audapter.

**Comment by cwnaber** [comment]
I think I generally agree that most of the stuff in current-studies/@new_heur should be merged into /@master soon. I do want to distinguish that current-studies/@master as it currently exists supports all of these heuristics, except that there's not a way to edit the third parameter of INTENSITY_AND_RATIO_ABOVE_THRESH from within audapter_viewer. (I just added INTENSITY_SLOPE_ABOVE_THRESH to the dropdown list.)

We should probably have the "what do we do about audapter_viewer?" conversation somewhere else.

**Comment by rpkarlin** [comment]
As far as I can tell things are functional, but remaining question is what use case INTENSITY_RATIO_BELOW_THRESH_NEG_SLOPE would have. I'm happy to leave it in but I'm not sure if it's that useful (and/or potentially based on a misunderstanding when I was trying to convey the idea for a ratio + ratio-slope heuristic)

**Comment by cwnaber** [comment]
I don't have a specific use case for INTENSITY_RATIO_BELOW_THRESH_NEG_SLOPE, and I don't remember the genesis of it as a heuristic at this point. I'll take it out since it sounds like it's not useful to you either.

**Pull request merged**
